FROM rust as builder
WORKDIR /usr/src/power-clash/
COPY Cargo.toml .
COPY Cargo.lock .

# This is a dummy build to get the dependencies cached.
RUN mkdir src \
    && echo "fn main() {}" > src/main.rs \
    && cargo build --release

COPY . .
RUN touch src/main.rs

# This works with the dummy project generated by `cargo new app --bin`
RUN cargo build --release

FROM rust:slim as runtime
COPY --from=builder /usr/src/power-clash/target/release/power-clash /usr/local/bin/power-clash
ENTRYPOINT ["/usr/local/bin/power-clash"]